[package]
name = "aoc"
version = "0.1.2022"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
evalexpr = "8.1.0"
regex = "1.7.0"
